version: '3.8'
services:
  spark:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    environment:
      - SPARK_MODE=master
    ports:
      - '8081:8080'
      - '7078:7077'
    volumes:
      - ..:/workspace

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    volumes:
      - ..:/workspace

  spark-client:
    build:
      context: ..
      dockerfile: docker/spark-client/Dockerfile
    image: local/spark-client:3.1.1
    depends_on:
      - spark
    volumes:
      - ..:/workspace
    networks:
      - default
